name: Build A21s Kernel (FINAL NO VDSO CRASH)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Reset source
      run: |
        git reset --hard
        git clean -fd

    - name: Fix apt
      run: |
        sudo sed -i 's|http://azure.archive.ubuntu.com|http://archive.ubuntu.com|g' /etc/apt/sources.list

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y build-essential bc bison flex libssl-dev libncurses-dev curl git ccache

    - name: Get clang
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

    - name: Fix linker
      run: |
        rm -f clang/bin/ld
        rm -f clang/bin/ld.lld

    - name: KernelSU
      run: |
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

    - name: Fix scripts
      run: |
        echo '#!/bin/sh' > scripts/min-tool-version.sh
        echo 'echo 0' >> scripts/min-tool-version.sh
        chmod +x scripts/min-tool-version.sh
        chmod -R +x scripts

    # 🔥 FIX VDSO CHUẨN
    - name: Fake vdso
      run: |
        mkdir -p arch/arm64/kernel/vdso
        touch arch/arm64/kernel/vdso/vdso.lds

    - name: Set env
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV

    - name: Clean
      run: |
        make mrproper

    - name: Build
      run: |
        export PATH=$PWD/clang/bin:$PATH

        make exynos850-a21snsxx_defconfig

        # 🔥 FIX interactive config
        yes "" | make olddefconfig

        make -j$(nproc) \
          CC=clang \
          HOSTCC=gcc \
          HOSTCXX=g++ \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi-

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: A21s-Kernel-KSU
        path: |
          arch/arm64/boot/Image.gz
          arch/arm64/boot/dts/**/*.dtb
